sudo: false

language: node_js

node_js:
  - '4.2'
  - '5'

matrix:
  allow_failures:
    - node_js: "5"

install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g jshint
  - npm install
